const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const P={dash:'M3 3h7v9H3zM14 3h7v5h-7zM14 12h7v9h-7zM3 16h7v5H3z',list:'M8 6h13M8 12h13M8 18h13M3 6h.01M3 12h.01M3 18h.01',plus:'M12 5v14M5 12h14',cal:'M3 5h18v16H3zM3 10h18M8 3v4M16 3v4',chart:'M4 20V10M10 20V4M16 20v-7M22 20H2',user:'M12 12a4 4 0 100-8 4 4 0 000 8zM4 21a8 8 0 0116 0',gear:'M12 15a3 3 0 100-6 3 3 0 000 6zM19 12h3M2 12h3M12 2v3M12 19v3M5 5l2 2M17 17l2 2M19 5l-2 2M7 17l-2 2',out:'M9 21H4V3h5M16 17l5-5-5-5M21 12H9',bell:'M6 8a6 6 0 0112 0c0 7 3 9 3 9H3s3-2 3-9M10 21h4',search:'M11 18a7 7 0 100-14 7 7 0 000 14zM21 21l-5-5',check:'M5 12l5 5 9-10',trash:'M4 7h16M9 7V4h6v3M6 7l1 14h10l1-14',edit:'M4 20h4L20 8l-4-4L4 16z',menu:'M3 6h18M3 12h18M3 18h18',moon:'M21 13A9 9 0 1111 3a7 7 0 0010 10z',clock:'M12 21a9 9 0 100-18 9 9 0 000 18zM12 7v5l3 2',folder:'M3 6h6l2 2h10v11H3z'};
const ic=n=>`<svg class="i" viewBox="0 0 24 24"><path d="${P[n]}"/></svg>`;
const off=n=>{const d=new Date();d.setDate(d.getDate()+n);return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')};
const fmt=s=>new Date(s+'T00:00').toLocaleDateString('en',{month:'short',day:'numeric'});
const ST=['To Do','In Progress','Completed'],PR=['Low','Medium','High'],CATS=['Study','Work','Personal','Health','Project'];
function seed(){return [['Finish DBMS assignment','Normalize the schema to 3NF and write the report.','In Progress','High','Study',1,-6],['Team stand-up notes','Summarise progress and blockers for the sprint review.','Completed','Low','Work',-1,-5],['Submit internship application','Attach resume and cover letter.','To Do','High','Personal',-2,-4],['Design login screen','Create wireframes for the auth flow.','In Progress','Medium','Project',3,-4],['Gym session','Leg day, 45 minutes.','To Do','Low','Health',0,-3],['Prepare project demo','Rehearse the 10-minute demo and record a backup video.','To Do','High','Project',4,-3],['Read OS chapter 5','Scheduling algorithms; make short notes.','Completed','Medium','Study',-3,-9],['Fix API bug #42','Task update endpoint returns 500 on empty description.','In Progress','High','Work',2,-2],['Plan weekend trip','Book tickets and split costs.','To Do','Low','Personal',6,-1],['Quarterly report draft','First draft of metrics and highlights.','To Do','Medium','Work',9,0]].map((t,i)=>({id:'t'+(i+1),title:t[0],description:t[1],status:t[2],priority:t[3],category:t[4],due:off(t[5]),created:off(t[6])}))}
function load(){try{const r=localStorage.getItem('tf1');if(r)return JSON.parse(r)}catch(e){}return{users:[{name:'Alex Johnson',email:'demo@taskflow.app',pw:'demo123',role:'Student'}],user:null,tasks:seed(),set:{email:true,browser:true,overdue:true,theme:'system'}}}
let S=load(),F={q:'',st:'',pr:'',dl:'',sort:'due'},CM=new Date(),RANGE='week';CM.setDate(1);
const save=()=>{try{localStorage.setItem('tf1',JSON.stringify(S))}catch(e){}};
/* API layer: swap these bodies with fetch('/api/tasks') calls to connect a real backend + database */
const api={async list(){return S.tasks},async create(t){t.id='t'+Date.now();t.created=off(0);S.tasks.unshift(t);save();return t},async update(id,p){const t=S.tasks.find(x=>x.id===id);Object.assign(t,p);save();return t},async remove(id){S.tasks=S.tasks.filter(x=>x.id!==id);save()}};
const cur=()=>S.users.find(u=>u.email===S.user),T=off(0),od=t=>t.status!=='Completed'&&t.due<T,byId=id=>S.tasks.find(t=>t.id===id);
const cnt=()=>({all:S.tasks.length,todo:S.tasks.filter(t=>t.status==='To Do').length,prog:S.tasks.filter(t=>t.status==='In Progress').length,done:S.tasks.filter(t=>t.status==='Completed').length,over:S.tasks.filter(od).length});
function toast(m){const e=document.createElement('div');e.className='toast';e.textContent=m;document.body.append(e);setTimeout(()=>e.remove(),2600)}
function theme(){const r=document.documentElement;S.set.theme==='system'?r.removeAttribute('data-theme'):r.dataset.theme=S.set.theme}
/* views */
const logo='<div class="logo"><span>'+ic('check')+'</span>TaskFlow</div>';
function landing(){const f=[['plus','Create Tasks','Capture ideas in seconds with titles, notes and categories.'],['chart','Track Progress','See completion rates and trends at a glance.'],['clock','Set Deadlines','Due dates and overdue alerts keep you on time.'],['folder','Organize Tasks','Filter by status, priority or deadline and sort your way.']];
return `<div class="wrap"><div class="nav">${logo}<div><a class="btn" href="#/login">Login</a></div></div>
<section class="hero"><h1>Manage Your Tasks Smarter</h1><p>TaskFlow helps students and professionals plan work, hit deadlines and see progress, all in one clean workspace.</p><a class="btn pri" href="#/signup">Get Started</a> <a class="btn" href="#/login">Login</a></section>
<div class="grid g4">${f.map(x=>`<div class="card hov"><div class="ficon">${ic(x[0])}</div><h3>${x[1]}</h3><p class="mu">${x[2]}</p></div>`).join('')}</div>
<div class="card mock"><div class="m"><div class="sb"></div><div><div class="grid g5" style="grid-template-columns:repeat(4,1fr)">${[['24','Total'],['8','Pending'],['9','In progress'],['7','Done']].map(s=>`<div class="card stat"><small>${s[1]}</small><b>${s[0]}</b></div>`).join('')}</div><div class="card" style="margin-top:14px"><small>Completion</small><div class="bar" style="margin-top:8px"><i style="width:68%"></i></div><div class="chart" style="height:80px">${[40,70,55,90,60,80,50].map(h=>`<div class="c"><div class="st"><i style="height:${h}%;background:var(--pr)"></i></div></div>`).join('')}</div></div></div></div></div>
<p class="mu" style="text-align:center;padding:36px 0">© 2026 TaskFlow · College project demo</p></div>`}
function auth(m){const s=m==='signup';return `<div class="auth"><div class="card"><div style="margin-bottom:18px">${logo}</div><h2>${s?'Create your account':'Welcome back'}</h2><p class="mu">${s?'Start organizing your tasks today.':'Log in to continue. Demo: demo@taskflow.app / demo123'}</p>
<form id="f-${m}" novalidate>${s?'<label>Name</label><input name="name" autocomplete="name">':''}<label>Email</label><input name="email" type="email" ${s?'':'value="demo@taskflow.app"'}><label>Password</label><input name="pw" type="password" ${s?'':'value="demo123"'}>${s?'<label>Confirm password</label><input name="pw2" type="password">':''}<div class="err" id="e"></div>
<button class="btn pri" style="width:100%;justify-content:center;margin-top:16px">${s?'Register':'Login'}</button></form>
<p class="mu" style="margin-top:14px;text-align:center">${s?'':'<a href="#" data-a="forgot" style="color:var(--pr)">Forgot password?</a> · '}${s?'Have an account? <a href="#/login" style="color:var(--pr)">Login</a>':'New here? <a href="#/signup" style="color:var(--pr)">Sign up</a>'}</p></div></div>`}
const NAV=[['dashboard','dash','Dashboard'],['tasks','list','My Tasks'],['new','plus','Create Task'],['calendar','cal','Calendar'],['analytics','chart','Analytics'],['profile','user','Profile'],['settings','gear','Settings']];
function shell(pg,body){const u=cur(),o=cnt().over;return `<nav class="side" id="side"><div style="padding:4px 8px 16px">${logo}</div>${NAV.map(n=>n[0]==='new'?`<button data-a="add">${ic(n[1])}${n[2]}</button>`:`<a href="#/${n[0]}" class="${pg===n[0]||(pg==='task'&&n[0]==='tasks')?'on':''}">${ic(n[1])}${n[2]}</a>`).join('')}<button data-a="logout" style="margin-top:auto">${ic('out')}Logout</button></nav>
<main class="main"><div class="top"><button class="ib menu" data-a="menu" aria-label="Menu">${ic('menu')}</button><div style="flex:1"></div><button class="ib" data-a="theme" aria-label="Toggle dark mode">${ic('moon')}</button><button class="ib" data-a="notif" aria-label="Notifications" style="position:relative">${ic('bell')}${o?`<span style="position:absolute;top:2px;right:2px;background:var(--er);color:#fff;font-size:10px;border-radius:9px;padding:0 5px">${o}</span>`:''}</button><div class="chip" style="padding:6px 12px">${esc(u.name)}</div></div>${body}</main>`}
const tr=t=>`<div class="card trow hov ${t.status==='Completed'?'dn':''}"><button class="ck" data-a="done" data-id="${t.id}" aria-label="Toggle complete">${ic('check')}</button><a class="tt" href="#/task/${t.id}"><b>${esc(t.title)}</b><small>${esc(t.category)} · Due ${fmt(t.due)}${od(t)?' · <span style="color:var(--er)">Overdue</span>':''}</small></a><span class="chip p-${t.priority}">${t.priority}</span><select data-st="${t.id}">${ST.map(s=>`<option ${s===t.status?'selected':''}>${s}</option>`).join('')}</select><button class="ib" data-a="edit" data-id="${t.id}" aria-label="Edit">${ic('edit')}</button><button class="ib" data-a="del" data-id="${t.id}" aria-label="Delete">${ic('trash')}</button></div>`;
const empty='<div class="card mu" style="text-align:center">No tasks here yet. Use "Add New Task" to create one.</div>';
function dashboard(){const c=cnt(),pc=c.all?Math.round(c.done/c.all*100):0,R=52,L=2*Math.PI*R,rec=[...S.tasks].sort((a,b)=>b.created.localeCompare(a.created)).slice(0,4),up=S.tasks.filter(t=>t.status!=='Completed'&&t.due>=T).sort((a,b)=>a.due.localeCompare(b.due)).slice(0,4);
const st=[['Total Tasks',c.all,'list'],['Pending',c.todo,'clock'],['In Progress',c.prog,'chart'],['Completed',c.done,'check'],['Overdue',c.over,'bell']];
return `<div class="top" style="margin-top:-8px"><div><h2>Welcome back, ${esc(cur().name.split(' ')[0])} 👋</h2><p class="mu">Here's what's on your plate today.</p></div><button class="btn pri" data-a="add">${ic('plus')}Add New Task</button></div>
<div class="grid g5">${st.map(s=>`<div class="card stat hov"><div class="ficon" style="width:34px;height:34px;margin-bottom:8px">${ic(s[2])}</div><small>${s[0]}</small><b style="${s[0]==='Overdue'&&s[1]?'color:var(--er)':''}">${s[1]}</b></div>`).join('')}</div>
<div class="grid g2" style="margin-top:16px"><div class="card" style="display:flex;align-items:center;gap:22px"><svg width="130" height="130" viewBox="0 0 130 130"><circle cx="65" cy="65" r="${R}" fill="none" stroke="var(--pl)" stroke-width="13"/><circle cx="65" cy="65" r="${R}" fill="none" stroke="var(--pr)" stroke-width="13" stroke-linecap="round" stroke-dasharray="${L*pc/100} ${L}" transform="rotate(-90 65 65)"/><text x="65" y="72" text-anchor="middle" font-size="24" font-weight="800" fill="var(--tx)">${pc}%</text></svg><div><h3>Task completion</h3><p class="mu">${c.done} of ${c.all} tasks completed.</p><a href="#/analytics" style="color:var(--pr);font-weight:600;font-size:14px">View analytics</a></div></div>
<div class="card"><h3 style="margin-bottom:10px">Upcoming deadlines</h3>${up.map(t=>`<a href="#/task/${t.id}" class="sw"><span>${esc(t.title)}</span><span class="chip">${t.due===T?'Today':fmt(t.due)}</span></a>`).join('')||'<p class="mu">Nothing due soon.</p>'}</div></div>
<h3 style="margin:22px 0 10px">Recent tasks</h3>${rec.map(tr).join('')}`}
function tasks(){return `<div class="top" style="margin-top:-8px"><h2>My Tasks</h2><button class="btn pri" data-a="add">${ic('plus')}Add New Task</button></div>
<div class="tools"><input id="q" placeholder="Search tasks…" value="${esc(F.q)}"><select id="fs"><option value="">All statuses</option>${ST.map(s=>`<option ${F.st===s?'selected':''}>${s}</option>`).join('')}</select><select id="fp"><option value="">All priorities</option>${PR.map(s=>`<option ${F.pr===s?'selected':''}>${s}</option>`).join('')}</select><select id="fd"><option value="">Any deadline</option><option value="over" ${F.dl==='over'?'selected':''}>Overdue</option><option value="today" ${F.dl==='today'?'selected':''}>Due today</option><option value="week" ${F.dl==='week'?'selected':''}>Next 7 days</option></select><select id="so">${[['due','Sort: Due date'],['pri','Sort: Priority'],['new','Sort: Newest'],['az','Sort: Title A–Z']].map(o=>`<option value="${o[0]}" ${F.sort===o[0]?'selected':''}>${o[1]}</option>`).join('')}</select></div><div id="list"></div>`}
function renderList(){const l=$('#list');if(!l)return;const q=F.q.toLowerCase(),w=off(7),rk={High:0,Medium:1,Low:2};
let a=S.tasks.filter(t=>(!q||(t.title+t.description+t.category).toLowerCase().includes(q))&&(!F.st||t.status===F.st)&&(!F.pr||t.priority===F.pr)&&(!F.dl||(F.dl==='over'?od(t):F.dl==='today'?t.due===T:t.due>=T&&t.due<=w)));
a.sort((x,y)=>F.sort==='pri'?rk[x.priority]-rk[y.priority]:F.sort==='new'?y.created.localeCompare(x.created):F.sort==='az'?x.title.localeCompare(y.title):x.due.localeCompare(y.due));l.innerHTML=a.map(tr).join('')||empty}
function task(id){const t=byId(id);if(!t)return '<p>Task not found. <a href="#/tasks" style="color:var(--pr)">Back to tasks</a></p>';const f=(k,v)=>`<div><small>${k}</small><div style="font-weight:600">${v}</div></div>`;
return `<a href="#/tasks" class="mu">← Back to tasks</a><div class="card" style="margin-top:12px;max-width:720px"><div style="display:flex;gap:10px;flex-wrap:wrap;margin-bottom:8px"><span class="chip s-${t.status}">${t.status}</span><span class="chip p-${t.priority}">${t.priority} priority</span>${od(t)?'<span class="chip p-High">Overdue</span>':''}</div><h2>${esc(t.title)}</h2><p style="margin:12px 0 18px" class="mu">${esc(t.description)||'No description.'}</p>
<div class="row2" style="margin-bottom:20px">${f('Category',esc(t.category))}${f('Status',t.status)}${f('Due date',fmt(t.due))}${f('Created',fmt(t.created))}</div><div style="display:flex;gap:10px;flex-wrap:wrap"><button class="btn pri" data-a="done" data-id="${t.id}">${ic('check')}${t.status==='Completed'?'Reopen':'Mark as completed'}</button><button class="btn" data-a="edit" data-id="${t.id}">${ic('edit')}Edit</button><button class="btn dg" data-a="del" data-id="${t.id}">${ic('trash')}Delete</button></div></div>`}
function calendar(){const y=CM.getFullYear(),m=CM.getMonth(),n=new Date(y,m+1,0).getDate(),s=CM.getDay();let h=['S','M','T','W','T','F','S'].map(d=>`<div class="h">${d}</div>`).join('')+'<div></div>'.repeat(s);
for(let d=1;d<=n;d++){const k=y+'-'+String(m+1).padStart(2,'0')+'-'+String(d).padStart(2,'0'),ts=S.tasks.filter(t=>t.due===k);h+=`<div class="d ${k===T?'td':''}" data-a="addd" data-d="${k}"><b>${d}</b>${ts.slice(0,2).map(t=>`<i>${esc(t.title)}</i>`).join('')}${ts.length>2?`<i>+${ts.length-2}</i>`:''}</div>`}
return `<div class="top" style="margin-top:-8px"><h2>${CM.toLocaleDateString('en',{month:'long',year:'numeric'})}</h2><div><button class="btn" data-a="cprev">←</button> <button class="btn" data-a="cnext">→</button></div></div><div class="card"><div class="cal">${h}</div></div><p class="mu" style="margin-top:10px">Click a day to add a task due that date.</p>`}
function analytics(){const c=cnt(),pc=c.all?Math.round(c.done/c.all*100):0,w=RANGE==='week',N=w?7:4,step=w?1:7,B=[];
for(let i=0;i<N;i++){const a=off(-(w?N-1-i:(N-1-i)*7-6)),b=off(-(w?N-1-i:(N-1-i)*7-6)+step-1),ts=S.tasks.filter(t=>t.due>=a&&t.due<=b);B.push({l:w?new Date(a+'T00:00').toLocaleDateString('en',{weekday:'short'}):'Wk '+(i+1),d:ts.filter(t=>t.status==='Completed').length,p:ts.filter(t=>t.status!=='Completed').length})}
const mx=Math.max(1,...B.map(b=>b.d+b.p)),ov=S.tasks.filter(od);
return `<div class="top" style="margin-top:-8px"><h2>Analytics</h2><div><button class="btn ${w?'pri':''}" data-a="range" data-r="week">Weekly</button> <button class="btn ${w?'':'pri'}" data-a="range" data-r="month">Monthly</button></div></div>
<div class="card"><div style="display:flex;justify-content:space-between"><h3>Overall progress</h3><b>${pc}%</b></div><div class="bar" style="margin:10px 0"><i style="width:${pc}%"></i></div><div style="display:flex;gap:8px;flex-wrap:wrap"><span class="chip s-To\ Do">${c.todo} to do</span><span class="chip s-In\ Progress">${c.prog} in progress</span><span class="chip s-Completed">${c.done} completed</span><span class="chip p-High">${c.over} overdue</span></div></div>
<div class="grid g2" style="margin-top:16px"><div class="card"><h3>Completed vs pending (${w?'last 7 days':'last 4 weeks'})</h3><p class="mu" style="margin-bottom:6px">Tasks grouped by due date.</p><div class="chart">${B.map(b=>`<div class="c"><div class="st"><i style="height:${b.p/mx*100}%;background:#93c5fd" title="${b.p} pending"></i><i style="height:${b.d/mx*100}%;background:var(--pr)" title="${b.d} done"></i></div><small>${b.l}</small></div>`).join('')}</div><p class="mu" style="margin-top:8px"><span style="color:var(--pr)">■</span> Completed &nbsp;<span style="color:#93c5fd">■</span> Pending</p></div>
<div class="card"><h3 style="margin-bottom:8px">Overdue notifications</h3>${ov.map(t=>`<a href="#/task/${t.id}" class="sw"><span>${esc(t.title)}</span><span class="chip p-High">${fmt(t.due)}</span></a>`).join('')||'<p class="mu">You are all caught up. No overdue tasks.</p>'}</div></div>`}
function profile(){const u=cur();return `<h2 style="margin-bottom:16px">Profile</h2><div class="grid g2"><form class="card" id="f-profile"><h3>Edit profile</h3><label>Name</label><input name="name" value="${esc(u.name)}"><label>Email</label><input name="email" type="email" value="${esc(u.email)}"><label>Role</label><select name="role">${['Student','Professional'].map(r=>`<option ${u.role===r?'selected':''}>${r}</option>`).join('')}</select><div class="err"></div><button class="btn pri" style="margin-top:14px">Save changes</button></form>
<form class="card" id="f-pw"><h3>Change password</h3><label>Current password</label><input name="c" type="password"><label>New password</label><input name="n" type="password"><label>Confirm new password</label><input name="n2" type="password"><div class="err"></div><button class="btn pri" style="margin-top:14px">Update password</button></form></div>`}
function settings(){const s=S.set,sw=(k,l)=>`<label class="sw" style="margin:0;font-weight:500">${l}<input type="checkbox" data-set="${k}" ${s[k]?'checked':''}></label>`;
return `<h2 style="margin-bottom:16px">Settings</h2><div class="grid g2"><div class="card"><h3>Notifications</h3>${sw('email','Email reminders for deadlines')}${sw('browser','Browser notifications')}${sw('overdue','Overdue task alerts')}</div><div class="card"><h3>Theme</h3><label>Appearance</label><select id="th">${['system','light','dark'].map(t=>`<option ${s.theme===t?'selected':''}>${t}</option>`).join('')}</select><button class="btn dg" data-a="logout" style="margin-top:22px">${ic('out')}Logout</button></div></div>`}
const V={dashboard,tasks,task,calendar,analytics,profile,settings};
function render(){theme();const pg=(location.hash.slice(2)||'').split('/'),p=pg[0],a=$('#app');
if(V[p]){if(!cur()){location.hash='#/login';return}a.innerHTML=shell(p,V[p](pg[1]));p==='tasks'&&renderList()}
else if(p==='login'||p==='signup'){if(cur()){location.hash='#/dashboard';return}a.innerHTML=auth(p)}else a.innerHTML=landing();scrollTo(0,0)}
/* task form modal */
function modal(t,d){t=t||{};$('#ov').innerHTML=`<div class="modal" data-a="close"><form class="card" id="f-task" data-id="${t.id||''}"><h2>${t.id?'Edit task':'New task'}</h2><label>Title</label><input name="title" value="${esc(t.title)}"><label>Description</label><textarea name="description" rows="3">${esc(t.description)}</textarea>
<div class="row2"><div><label>Status</label><select name="status">${ST.map(s=>`<option ${s===(t.status||'To Do')?'selected':''}>${s}</option>`).join('')}</select></div><div><label>Priority</label><select name="priority">${PR.map(s=>`<option ${s===(t.priority||'Medium')?'selected':''}>${s}</option>`).join('')}</select></div><div><label>Category</label><input name="category" list="cats" value="${esc(t.category||'Study')}"><datalist id="cats">${CATS.map(c=>`<option>${c}</option>`).join('')}</datalist></div><div><label>Due date</label><input name="due" type="date" value="${t.due||d||off(1)}"></div></div><div class="err"></div><div style="display:flex;gap:10px;justify-content:flex-end;margin-top:18px"><button type="button" class="btn" data-a="close">Cancel</button><button class="btn pri">${t.id?'Save changes':'Create task'}</button></div></form></div>`;$('#f-task input').focus()}
const close=()=>$('#ov').innerHTML='';
async function setStatus(id,s){await api.update(id,{status:s});render();toast(s==='Completed'?'Task completed':'Status updated')}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-a]');if(!b)return;const a=b.dataset.a,id=b.dataset.id;
if(a==='close'){if(e.target!==b&&b.classList.contains('modal'))return;close()}
else if(a==='add'){modal();$('#side')?.classList.remove('open')}else if(a==='addd')modal(null,b.dataset.d);else if(a==='edit')modal(byId(id));
else if(a==='done'){const t=byId(id);setStatus(id,t.status==='Completed'?'To Do':'Completed')}
else if(a==='del'){if(confirm('Delete this task?')){await api.remove(id);close();if(location.hash.startsWith('#/task/'))location.hash='#/tasks';else render();toast('Task deleted')}}
else if(a==='logout'){S.user=null;save();location.hash='#/login';render()}else if(a==='menu')$('#side').classList.toggle('open');
else if(a==='theme'){S.set.theme=document.documentElement.dataset.theme==='dark'?'light':'dark';save();theme()}
else if(a==='notif'){const o=S.tasks.filter(od);toast(o.length?`${o.length} overdue: ${o.map(t=>t.title).slice(0,2).join(', ')}${o.length>2?'…':''}`:'No overdue tasks')}
else if(a==='cprev'||a==='cnext'){CM.setMonth(CM.getMonth()+(a==='cnext'?1:-1));render()}else if(a==='range'){RANGE=b.dataset.r;render()}
else if(a==='forgot'){e.preventDefault();toast('Demo only: a reset link would be emailed here')}});
document.addEventListener('change',e=>{const t=e.target;if(t.dataset.st)setStatus(t.dataset.st,t.value);
else if(t.id==='fs'){F.st=t.value;renderList()}else if(t.id==='fp'){F.pr=t.value;renderList()}else if(t.id==='fd'){F.dl=t.value;renderList()}else if(t.id==='so'){F.sort=t.value;renderList()}
else if(t.dataset.set){S.set[t.dataset.set]=t.checked;save();toast('Settings saved');if(t.checked&&t.dataset.set==='browser'&&window.Notification)try{Notification.requestPermission()}catch(x){}}
else if(t.id==='th'){S.set.theme=t.value;save();theme()}});
document.addEventListener('input',e=>{if(e.target.id==='q'){F.q=e.target.value;renderList()}});
document.addEventListener('keydown',e=>{if(e.key==='Escape')close()});
document.addEventListener('submit',async e=>{e.preventDefault();const f=e.target,d=Object.fromEntries(new FormData(f)),er=f.querySelector('.err'),bad=m=>{er.textContent=m},mail=/^\S+@\S+\.\S+$/;
if(f.id==='f-login'){const u=S.users.find(x=>x.email===d.email.trim().toLowerCase()&&x.pw===d.pw);if(!mail.test(d.email))return bad('Enter a valid email address.');if(!u)return bad('Email or password is incorrect.');S.user=u.email;save();location.hash='#/dashboard';render()}
else if(f.id==='f-signup'){if(!d.name.trim())return bad('Enter your name.');if(!mail.test(d.email))return bad('Enter a valid email address.');if(d.pw.length<6)return bad('Password needs at least 6 characters.');if(d.pw!==d.pw2)return bad('Passwords do not match.');if(S.users.some(x=>x.email===d.email.toLowerCase()))return bad('An account with this email already exists.');
S.users.push({name:d.name.trim(),email:d.email.toLowerCase(),pw:d.pw,role:'Student'});S.user=d.email.toLowerCase();save();location.hash='#/dashboard';render();toast('Account created')}
else if(f.id==='f-task'){if(!d.title.trim())return bad('Give the task a title.');if(!d.due)return bad('Pick a due date.');d.title=d.title.trim();d.category=d.category.trim()||'General';const id=f.dataset.id;id?await api.update(id,d):await api.create(d);close();render();toast(id?'Task updated':'Task created')}
else if(f.id==='f-profile'){if(!d.name.trim()||!mail.test(d.email))return bad('Enter a name and a valid email.');const u=cur();Object.assign(u,{name:d.name.trim(),email:d.email.toLowerCase(),role:d.role});S.user=u.email;save();render();toast('Profile saved')}
else if(f.id==='f-pw'){const u=cur();if(d.c!==u.pw)return bad('Current password is incorrect.');if(d.n.length<6)return bad('New password needs at least 6 characters.');if(d.n!==d.n2)return bad('Passwords do not match.');u.pw=d.n;save();f.reset();toast('Password updated')}});
addEventListener('hashchange',render);render();